name: maxent-r1
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - cuda-toolkit=12.4
  - ninja
  - pip:
      - uv
      - vllm==0.7.2
      - setuptools==75.8.0
